config/routes.rb
Rails.application.routes.draw do
	
	get '@' + ':id', to: 'profile#show', :as => :profile
	get 'fresh', to: 'posts#fresh', :as => :fresh_posts
	devise_for :users, path: "auth", path_names: { sign_in: 'sign_in', sign_out: 'sign_out', password: 'password', confirmation: 'verification', registration: 'register', sign_up: 'cmon_let_me_in' }
	root to: "posts#best"
	
	resources :posts, path_names: { new: 'new-story' }, :path => '' do
		member do
			patch 'karma_up', to: 'posts#karma_up'
        	patch 'karma_down', to: 'posts#karma_down'
		end
	end
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :title, presence: true, length: { minimum: 2 }
	validates :body, presence: true, length: { minimum: 5 }
	validates :user_id, presence: true

	belongs_to :user

	acts_as_votable

	before_create :create_slug

	def create_slug
    	self.slug = self.title.parameterize
  	end

  	def to_param
    	slug
  	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	
	validates :email, presence: true, uniqueness: true
	validates :name, presence: true, uniqueness: true

  has_many :posts, dependent: :destroy

  acts_as_voter
	
	before_create :downcase_name, :downcase_email

	def to_param
    name
  end

  def downcase_name
  	self.name = name.downcase
  end

  def downcase_email
    self.email = email.downcase
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  add_flash_types :success, :error, :notice
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) << :name
    devise_parameter_sanitizer.for(:sign_up) << :name
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :karma_up, :karma_down]
	before_action :set_post, only: [:show, :edit, :update, :destroy, :karma_up, :karma_down]

	def best
		@posts = Post.order(:cached_votes_total => :desc).paginate(:page => params[:page], :per_page => 7)
	end

  def fresh
    @posts = Post.order(created_at: :desc).paginate(:page => params[:page], :per_page => 7)
  end

	def show
	end

	def new
		@post = current_user.posts.new
	end

	def edit
	end

	def create
		@post = current_user.posts.new(post_params)

		respond_to do |format|
    		if @post.save
        		format.html { redirect_to @post, notice: 'Article was successfully created.' }
        		format.json { render :show, status: :created, location: @post }
      		else
        		format.html { render :new }
        		format.json { render json: @post.errors, status: :unprocessable_entity }
      		end
    	end
	end

	def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def karma_up
    @post.liked_by current_user

    respond_to do |format|
      format.html { redirect_to @post, notice: "Thank you #{current_user.name.capitalize} for voting up!" }
      format.js {}
    end
  end

  def karma_down
    @post.unliked_by current_user

    respond_to do |format|
      format.html { redirect_to @post, notice: "Thank you for voting!" }
      format.js {}
    end
  end

  private

  	def set_post
      	@post = Post.find_by_slug(params[:id])
    end

    def post_params
    	params[:post].permit(:title, :body)
    end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
	def show
		@user = User.find_by_name(params[:id])
		@posts = @user.posts.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def karma_for(user)
		@posts = user.posts.all
		@karma = @posts.inject(0){|sum, post| sum + post.votes_for.size}
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="row">
    <div class="small-6 columns clearfix">
      <a href="https://github.com/alexbtlv/karma_blogger"><i class="fa fa-github fa-2x right"></i></a>
    </div>
    <div class="small-6 columns clearfix">
        <a href="https://twitter.com/Alexbtlv"><i class="fa fa-twitter fa-2x left"></i></a>
    </div>
  </div>
  <div class="row">
    <div class="small-12 column">
      <h5 class="text-center"><small>A simple Rails blogging app. A winning entry for <a href="http://teamtreehouse.com/">treehouse</a> forum contest by <a href="http://teamtreehouse.com/alexanderbatalov">Alexander Batalov.</a></small></h5>
    </div>
  </div>  
</footer>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-26994640-2', 'auto');
  ga('send', 'pageview');
</script>

app/views/layouts/_navbar.html.erb
<div class="fixed">
  <nav class="top-bar" data-topbar>
    <ul class="title-area">
      <li class="name">
        <h1><%= link_to "Karma Blogger", root_path %></h1>
      </li>
       <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>

    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">
      	<% if user_signed_in? %>
      	<li><%= link_to content_tag(:i,"New Story", :class=>"fa fa-pencil-square-o fa-lg"), new_post_path %></li>
      	<li class="has-dropdown">
         	<a href="#"><i class="fa fa-lg"><%= current_user.name.split.map(&:capitalize)*' ' %></i></a>
          <ul class="dropdown list-group">
            <li><%= link_to content_tag(:i,"Profile", :class=>"fa fa-user fa-lg"), profile_path(current_user) %></li>
            <li><%= link_to content_tag(:i,"Settings", :class=>"fa fa-cog fa-lg"), edit_user_registration_path(current_user) %></li>
            <li><%= link_to content_tag(:i,"Sign Out", :class=>"fa fa-sign-out fa-lg"), destroy_user_session_path, class: "list-group-item", method: :delete %></li>
          </ul>
        </li>
  	    <% else %>
        <li>
          <%= link_to content_tag(:i,"Sign Up", :class=>"fa fa-users fa-lg"), new_user_registration_path %>
        </li>
  	    <li>
  	    	<%= link_to content_tag(:i,"Sign In", :class=>"fa fa-sign-in fa-lg"), new_user_session_path %>
  	    </li>
  	    <% end %>
      </ul>

      <!-- Left Nav Section -->
      <ul class="left">
        <li><%= link_to content_tag(:i,"Best Reading", :class=>"fa fa-book fa-lg"), root_path %></li>
        <li><%= link_to content_tag(:i,"Fresh Articles", :class=>"fa fa-leaf fa-lg"), fresh_posts_path %></li>
      </ul>
    </section>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "Karma Blogger" %></title>
    <script src="http://d3js.org/d3.v3.min.js"></script>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">
    <div id="wrapper">
      <%= render partial: 'layouts/navbar' %>
      <% flash.each do |type, message| %>
      <div data-alert class="flash alert-box text-center <%= type %>">
        <%= message %>
          <a href="#" class="close">&times;</a>
      </div>
      <% end %>
      <div id="content">
        <%= yield %>
      </div>
      <%= render partial: 'layouts/footer' %>
      <%= javascript_include_tag "application" %>
    </div>
  </body>
</html>

app/views/posts/_karma.html.erb
<h1 class="text-center karma-counter"><%= @post.votes_for.size %></h1>
<% if user_signed_in? %>
	<% if current_user.voted_for? @post %>
		<h5 class="text-center"> <%= link_to "Karma", karma_down_post_path(@post), remote: true, method: :patch %></h5>
	<% else %>
		<h5 class="text-center"><%= link_to "Karma", karma_up_post_path(@post), remote: true, method: :patch %></h5>
	<% end %>
<% else %>
	<h5 class="text-center"><%= link_to "Karma", karma_up_post_path(@post), method: :patch %></h5>
<% end %>

app/views/posts/_post_preview.html.erb
<% @posts.each do |post| %>
	<div class="preview">
		<div class="small-10 column">
			<div class="small-12 column">
				<h6 class="subheader">Written by <%= link_to post.user.name.split.map(&:capitalize)*' ', profile_path(post.user) %></h6>
			</div>
			<div class="small-12 columns truncate" title="<%= post.title.capitalize %>">
				<h3 class="truncate" title="<%= post.title.capitalize %>"><%= link_to post.title.capitalize, post_path(post) %></h3>
			</div>
			<div class="small-12 columns">
				<p class="truncate"><%= post.body %></p>
			</div>
			<div class="small-12 column" id="liked-by">	
				<% if post.cached_votes_total > 1 %>
					<em>Liked by <%= link_to User.find(post.get_likes.last.voter_id).name.split.map(&:capitalize)*' ', profile_path(User.find(post.get_likes.last.voter_id)) %> and more...</em>
				<% end %>
			</div>
		</div>
		<div class="small-2 column karma-wrapper">
			<h1 class="text-center karma-counter"><%= post.votes_for.size %></h1>
		</div>
		<hr>
	</div>
<% end %>

app/views/posts/best.html.erb
<div id="trianglify">
	<div class="row">
		<div class="small-12 small-centered columns">
			<h1 class="text-center">A simple blogging app</h1>
		</div>
	</div>
</div>
<div class="row collapse">
    <div class="small-12 small-centered columns">
     <%= render partial: 'post_preview' %>
	</div>
</div>
<div class="row">
	<div class="small-12 small-centered column">
		<div class="pagination-centered">
			<%= will_paginate @posts, renderer: FoundationPagination::Rails %>
		</div>
	</div>
</div>

app/views/posts/edit.html.erb
<div class="row">
	<div class="small-12 column">
		<h2 class="text-center">Edit Article</h2><br/>
		<h3 class="text-center"><%= @post.title %></h3>
	</div>
    <div class="small-6 small-centered medium-4 medium-centered large-2 large-centered columns">
      <hr>
    </div>
	<div class="small-12 small-centered medium-10 medium-centered large-8 large-centered columns">
		<%= form_for(@post) do |f| %>
			<div class="preview">	
				<div class="row">
					<div class="small-12 column">
						<%= f.label :title, "Title" %>
						<%= f.text_field :title, :placeholder => "Are you sure you want to delete title?" %>
					</div>
				</div>
				<div class="row">
					<div class="small-12 column">
						<%= f.label :body, "Article" %>
						<%= f.text_area :body, id: "expand",:placeholder => "Either write something worth reading or do something worth writing. Benjamin Franklin"  %>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="small-6 small-centered column">
					<%= f.submit "Update", class: "button round expand" %>
					<%= link_to "Delete Article", @post, method: :delete, class: 'button alert round expand', data: { confirm: "Are you sure?" } %>
				</div>
		  	</div>
		<% end %>
	</div>
</div>

app/views/posts/fresh.html.erb
<div id="trianglify">
	<div class="row">
		<div class="small-12 small-centered columns">
			<h1 class="text-center">A simple blogging app</h1>
		</div>
	</div>
</div>
<div class="row collapse">
    <div class="small-12 small-centered columns">
		<%= render partial: 'post_preview' %>
	</div>
</div>
<div class="row">
	<div class="pagination-centered">
		<%= will_paginate @posts, renderer: FoundationPagination::Rails %>
	</div>
</div>

app/views/posts/index.html.erb
<div id="trianglify">
	<div class="row">
		<div class="small-12 small-centered columns">
			<h1 class="text-center">A simple blogging app</h1>
		</div>
	</div>
</div>
<div class="row collapse">
    <div class="small-12 small-centered columns">
		<% @posts.each do |post| %>
			<div class="preview">
				<div class="small-10 column">
					<div class="small-12 column">
						<h6 class="subheader">Written by <%= link_to post.user.name.capitalize, profile_path(post.user) %></h6>
					</div>
					<div class="small-12 columns truncate" title="<%= post.title.capitalize %>">
						<h3 class="truncate" title="<%= post.title.capitalize %>"><%= link_to post.title.capitalize, post_path(post) %></h3>
					</div>
					<div class="small-12 columns">
						<p class="truncate"><%= post.body %></p>
					</div>	
				</div>
				<div class="small-2 column karma-wrapper">
					<h1 class="text-center karma-counter"><%= post.votes_for.size %></h1>
				</div>
				<hr>
			</div>
		<% end %>
	</div>
</div>
<div class="row">
	<div class="pagination-centered">
		<%= will_paginate @posts, renderer: FoundationPagination::Rails %>
	</div>
</div>

app/views/posts/karma_down.js.erb
$("#karma").html("<%= escape_javascript(render('karma')) %>")

app/views/posts/karma_up.js.erb
$("#karma").html("<%= escape_javascript(render('karma')) %>")

app/views/posts/new.html.erb
<div id="trianglify">
	<div class="row">
		<div class="small-12 small-centered columns">
			<h1 class="text-center">Write your story</h1>
		</div>
	</div>
</div>
<div class="row">
	<div class="small-12 small-centered medium-10 medium-centered large-8 large-centered columns">
		<%= form_for(@post) do |f| %>
			<div class="preview">	
				<div class="row">
					<div class="small-12 column">
						<%= f.label :title, "Title here" %>
						<%= f.text_field :title, :placeholder => "Start typing your idea here..." %>
					</div>
				</div>
				<div class="row">
					<div class="small-12 column">
						<%= f.label :body, "Article" %>
						<%= f.text_area :body, id: "expand",:placeholder => "Either write something worth reading or do something worth writing. Benjamin Franklin"  %>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="small-6 small-centered column">
					<%= f.submit "Publish", class: "button round expand" %>
				</div>
		  	</div>
		<% end %>
	</div>
</div>

app/views/posts/show.html.erb
<div id="author" class="row">
	<div class="small-12 small-centered medium-12 medium-centered large-10 large-centered columns">
		<h3><%= link_to @post.user.name.upcase, profile_path(@post.user) %></h3>
	</div>
</div>
<div class="row">
	<div class="small-12 small-centered medium-12 medium-centered large-10 large-centered columns">
		<h1><%= @post.title %></h1>
	</div>
</div>
<div class="row">
	<div class="small-12 small-centered medium-12 medium-centered large-10 large-centered columns">
		<p><%= simple_format(@post.body) %></p>
	</div>
</div>
<div class="row">
	<div class="small-12 small-centered medium-12 medium-centered large-10 large-centered columns">
		<em>
			By <%= link_to @post.user.name.capitalize, profile_path(@post.user) %> <%= time_ago_in_words(@post.created_at)%> ago.
		</em>
		<% if @post.user == current_user %>
			<em><%= link_to "Edit Article", edit_post_path(@post) %></em>
		<% end %>
	</div>
</div>
<div class="row">
	<div class="small-6 small-centered medium-4 medium-centered large-2 large-centered columns">
		<div id="karma">
			<%= render 'karma' %>
		</div>
	</div>
</div>